import React, { useState } from 'react';
import { ShieldCheck, ShieldAlert, FileText, CheckCircle2, Lock } from 'lucide-react';

export default function LegalModal({ isOpen, onClose, termsAccepted, onAcceptTerms, legalData }) {
  const [agreed, setAgreed] = useState(termsAccepted);
  const [loading, setLoading] = useState(false);

  if (!isOpen) return null;

  const handleConfirm = async () => {
    if (!agreed) return;
    setLoading(true);
    try {
      await onAcceptTerms();
      onClose();
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const clauses = legalData?.clauses || [
    {
      id: "advisory_only",
      heading: "1. Advisory Nature of Agent Intelligence",
      content: "All insights, pricing recommendations, capital reallocations, inventory reorder suggestions, and marketing copy generated by Diligent and its subagents are strictly algorithmic and advisory in nature. Diligent does not guarantee specific revenue gains, footfall surges, or margins."
    },
    {
      id: "liability_abstraction",
      heading: "2. Assumption of Operational and Financial Risk",
      content: "The business owner/merchant assumes 100% legal, financial, and regulatory responsibility for any operational adjustments, price alterations, public advertisements, employee management shifts, or vendor orders made in reliance upon Diligent's swarm outputs."
    },
    {
      id: "human_in_the_loop",
      heading: "3. Human-in-the-Loop Safeguards",
      content: "Autonomous execution of e-commerce storefront modifications, automated POS price adjustments, and bulk marketing dispatch require explicit merchant authorization via the Safeguard Confirmation Gateway."
    },
    {
      id: "data_confidentiality",
      heading: "4. Enterprise Data Privacy & Telemetry",
      content: "Business telemetry, including POS barcode logs, customer CRM profiles, and payroll metrics, are processed in strict isolation and encrypted in transit and at rest."
    }
  ];

  return (
    <div style={{
      position: 'fixed',
      inset: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.85)',
      backdropFilter: 'blur(10px)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 100,
      padding: '20px'
    }}>
      <div className="glass-panel" style={{
        maxWidth: '680px',
        width: '100%',
        maxHeight: '90vh',
        overflowY: 'auto',
        padding: '32px',
        backgroundColor: '#0c1322',
        border: '1px solid rgba(56, 189, 248, 0.3)',
        boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.7)'
      }}>
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '14px', marginBottom: '20px' }}>
          <div style={{
            width: '46px',
            height: '46px',
            borderRadius: '12px',
            backgroundColor: 'rgba(2, 132, 199, 0.15)',
            border: '1px solid rgba(2, 132, 199, 0.3)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center'
          }}>
            <ShieldAlert size={26} color="#38bdf8" />
          </div>
          <div>
            <h2 style={{ fontSize: '1.3rem', fontWeight: 800, color: '#ffffff' }}>
              Legal & Compliance Gateway
            </h2>
            <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
              Mandatory Liability Abstraction & Advisory Disclaimer (Microsoft Hack with Hyderabad 3.0)
            </p>
          </div>
        </div>

        {/* Notice Banner */}
        <div style={{
          backgroundColor: 'rgba(245, 158, 11, 0.08)',
          border: '1px solid rgba(245, 158, 11, 0.3)',
          padding: '14px 18px',
          borderRadius: '10px',
          marginBottom: '20px',
          display: 'flex',
          gap: '12px',
          alignItems: 'flex-start'
        }}>
          <Lock size={18} color="#fbbf24" style={{ flexShrink: 0, marginTop: '2px' }} />
          <p style={{ fontSize: '0.82rem', color: '#fde68a', lineHeight: 1.5 }}>
            <strong>Liability Abstraction Notice:</strong> Diligent acts as an autonomous advisory consultant. Before unleashing multi-agent actions, marketing broadcasts, or inventory capital reallocations, merchant confirmation is required.
          </p>
        </div>

        {/* Clauses Scroll Area */}
        <div style={{
          backgroundColor: 'rgba(0, 0, 0, 0.35)',
          border: '1px solid var(--border-color)',
          borderRadius: '10px',
          padding: '18px',
          marginBottom: '24px',
          display: 'flex',
          flexDirection: 'column',
          gap: '16px',
          maxHeight: '320px',
          overflowY: 'auto'
        }}>
          {clauses.map(clause => (
            <div key={clause.id} style={{ borderBottom: '1px solid rgba(255, 255, 255, 0.05)', paddingBottom: '12px' }}>
              <h4 style={{ fontSize: '0.88rem', fontWeight: 700, color: '#38bdf8', marginBottom: '4px' }}>
                {clause.heading}
              </h4>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', lineHeight: 1.6 }}>
                {clause.content}
              </p>
            </div>
          ))}
        </div>

        {/* Agreement Checkbox */}
        <div style={{
          display: 'flex',
          alignItems: 'flex-start',
          gap: '12px',
          marginBottom: '24px',
          cursor: 'pointer'
        }} onClick={() => setAgreed(!agreed)}>
          <input
            type="checkbox"
            checked={agreed}
            onChange={(e) => setAgreed(e.target.checked)}
            style={{ width: '18px', height: '18px', marginTop: '2px', accentColor: '#0284c7', cursor: 'pointer' }}
          />
          <label style={{ fontSize: '0.84rem', color: '#ffffff', cursor: 'pointer', userSelect: 'none' }}>
            I acknowledge that <strong>Diligent</strong> provides algorithmic advisory consulting. As the verified merchant operator of <strong>Sri Balaji Smart Retail & Tech Mart</strong>, I assume 100% legal, financial, and operational liability for all executed recommendations.
          </label>
        </div>

        {/* Buttons */}
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px' }}>
          {termsAccepted && (
            <button
              className="btn-secondary"
              onClick={onClose}
            >
              Close
            </button>
          )}
          <button
            className="btn-primary"
            disabled={!agreed || loading}
            style={{ opacity: agreed ? 1 : 0.5, cursor: agreed ? 'pointer' : 'not-allowed' }}
            onClick={handleConfirm}
          >
            <CheckCircle2 size={16} />
            <span>{loading ? 'Logging Agreement...' : termsAccepted ? 'Re-confirm Agreement' : 'Accept Terms & Enter Command Center'}</span>
          </button>
        </div>
      </div>
    </div>
  );
}
